### ISSUE TITLE
Question about materials: Can I export FBX Embedded textures as texture2d or TArray<uint8> format?

### ISSUE THREAD

**Issue by NounKim** [irajsb/UE4_Assimp#10]
Question about materials: Can I export FBX Embedded textures as texture2d or TArray<uint8> format? If this feature is not supported, how can I fix it?

**Comment by irajsb** [comment]
https://github.com/irajsb/UE4_Assimp/releases/tag/5.4.2EmbeddedTextureImport

**Comment by NounKim** [comment]
Great! What a Nice Developer!
