### ISSUE TITLE
Can Assimp Lib also recognize FBX Embedded textures that are not recognized by Unreal?

### ISSUE THREAD

**Issue by NounKim** [irajsb/UE4_Assimp#11]
Unreal seems to only recognize Embedded Textures in certain paths in the FBX. Assimp seems to be similar to Unreal. The scene->GetEmbeddedTexture() function does not recognize Embedded Textures that are not recognized by Unreal. I wonder if this is because I'm not very good at using the Assimp library or if the Assimp library depends on a specific path in the FBX.

An example of this is the FBX exported from Unreal.

If the FBX has a texture embedded, if you remove the texture created in the absolute path, Unreal will assume that the FBX doesn't have a texture, but if you use the FBX viewer you will still see the textured model.

**Comment by irajsb** [comment]
Embedded texture is a texture that is added inside the FBX. FBX can have two ways to load textures one is having a path to texture and second one is embedded texture. so if the texture is outside of the FBX file its not embedded at all .
![Screenshot 2022-06-08 141948](https://user-images.githubusercontent.com/36444724/172587513-3c8e4497-9105-413f-a2c3-ea7f4e40f1a6.png)
if you want to embed textures in blender set path to copy and click on box icon beside it

**Comment by NounKim** [comment]
> Embedded texture is a texture that is added inside the FBX. FBX can have two ways to load textures one is having a path to texture and second one is embedded texture. so if the texture is outside of the FBX file its not embedded at all . FBX files that have external textures can lose their textures if the files are not moved correctly so its better to embed the textures inside the fbx file itself . ![Screenshot 2022-06-08 141948](https://user-images.githubusercontent.com/36444724/172587513-3c8e4497-9105-413f-a2c3-ea7f4e40f1a6.png) if you want to embed textures in blender set path to copy and click on box icon beside it

What I mean is when Assimp doesn't recognize it even though it has an embedded texture.

**Comment by irajsb** [comment]
Did you try the sample project that I provided?
