### ISSUE TITLE
Crash on importing models without normals.

### ISSUE THREAD

**Issue by kalluwa** [irajsb/UE4_Assimp#15]
thanks for sharing this great work.
I can load FBX format correctly but
when i am trying to test other format ( .obj .ply) , ue crashed and exit :
![image](https://user-images.githubusercontent.com/9412335/178253400-de8b1547-77f7-44af-89ae-dfe4e9380e25.png)

using lastest release [5.4.2 texture support]

**Comment by irajsb** [comment]
can you provide the file you are testing with ?

**Comment by kalluwa** [comment]
here is the file i tested:
[bunny.zip](https://github.com/irajsb/UE4_Assimp/files/9084505/bunny.zip)

and my environment is UE5.0
