### ISSUE TITLE
LINK : fatal error LNK1181

### ISSUE THREAD

**Issue by inealey** [irajsb/UE4_Assimp#18]
**Describe the bug**
When following the build instructions, the build at step 4: Build Unreal Project fails while linking against assimp. 

**To Reproduce**

Platform:
Windows 11
Unreal Engine 4.27.2
Visual Studio 2022

1) create a new UE4 project
2) follow instructions at https://github.com/irajsb/UE4_Assimp/wiki/How-To-Build

**Logs**
Here is the full output from VS:

Build started...
1>------ Build started: Project: UE4_Assimp_Test, Configuration: Development_Editor x64 ------
1>Invalidating makefile for UE4_Assimp_TestEditor (UE_Assimp.uplugin has been added)
1>Copying D:\Unreal Projects\UE4_Assimp_Test\Plugins\UE4_Assimp\Source\ThirdParty\UE_AssimpLibrary\assimp\bin\Release\assimp.dll to D:\Unreal Projects\UE4_Assimp_Test\Plugins\UE4_Assimp\Binaries\Win64\assimp.dll
1>Failed to copy file: Could not find a part of the path 'D:\Unreal Projects\UE4_Assimp_Test\Plugins\UE4_Assimp\Source\ThirdParty\UE_AssimpLibrary\assimp\bin\Release\assimp.dll'.
1>UnrealBuildTool : warning : Library 'D:\Unreal Projects\UE4_Assimp_Test\Plugins\UE4_Assimp\Source\ThirdParty\UE_AssimpLibrary\assimp\lib\Release\assimp.lib' was not resolvable to a file when used in Module 'UE_AssimpLibrary', assuming it is a filename and will search library paths for it. This is slow and dependency checking will not work for it. Please update reference to be fully qualified alternatively use PublicSystemLibraryPaths if you do intended to use this slow path to suppress this warning.
1>Parsing headers for UE4_Assimp_TestEditor
1>  Running UnrealHeaderTool "D:\Unreal Projects\UE4_Assimp_Test\UE4_Assimp_Test.uproject" "D:\Unreal Projects\UE4_Assimp_Test\Intermediate\Build\Win64\UE4_Assimp_TestEditor\Development\UE4_Assimp_TestEditor.uhtmanifest" -LogCmds="loginit warning, logexit warning, logdatabase error" -Unattended -WarningsAsErrors -abslog="C:\Users\isaac\AppData\Local\UnrealBuildTool\Log_UHT.txt" -installed
1>LogInit: Display: Loading text-based GConfig....
1>Reflection code generated for UE4_Assimp_TestEditor in 4.0002073 seconds
1>Building UE4_Assimp_TestEditor...
1>Using Visual Studio 2022 14.33.31629 toolchain (C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.33.31629) and Windows 10.0.22000.0 SDK (C:\Program Files (x86)\Windows Kits\10).
1>Building 8 actions with 16 processes...
1>  [1/8] Default.rc2
1>  [2/8] UE4Editor-UE4_Assimp_Test-0001.lib
1>     Creating library D:\Unreal Projects\UE4_Assimp_Test\Intermediate\Build\Win64\UE4Editor\Development\UE4_Assimp_Test\UE4Editor-UE4_Assimp_Test-0001.lib and object D:\Unreal Projects\UE4_Assimp_Test\Intermediate\Build\Win64\UE4Editor\Development\UE4_Assimp_Test\UE4Editor-UE4_Assimp_Test-0001.exp
1>  [3/8] UE4Editor-UE4_Assimp_Test-0001.dll
1>     Creating library D:\Unreal Projects\UE4_Assimp_Test\Intermediate\Build\Win64\UE4Editor\Development\UE4_Assimp_Test\UE4Editor-UE4_Assimp_Test-0001.suppressed.lib and object D:\Unreal Projects\UE4_Assimp_Test\Intermediate\Build\Win64\UE4Editor\Development\UE4_Assimp_Test\UE4Editor-UE4_Assimp_Test-0001.suppressed.exp
1>  [4/8] Module.UE_Assimp.gen.cpp
1>  [5/8] Module.UE_Assimp.cpp
1>  [6/8] UE4Editor-UE_Assimp-0001.lib
1>     Creating library D:\Unreal Projects\UE4_Assimp_Test\Plugins\UE4_Assimp\Intermediate\Build\Win64\UE4Editor\Development\UE_Assimp\UE4Editor-UE_Assimp-0001.lib and object D:\Unreal Projects\UE4_Assimp_Test\Plugins\UE4_Assimp\Intermediate\Build\Win64\UE4Editor\Development\UE_Assimp\UE4Editor-UE_Assimp-0001.exp
1>  [7/8] UE4Editor-UE_Assimp-0001.dll
1>LINK : fatal error LNK1181: cannot open input file 'D:\Unreal Projects\UE4_Assimp_Test\Plugins\UE4_Assimp\Source\ThirdParty\UE_AssimpLibrary\assimp\lib\Release\assimp.lib'
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Microsoft\VC\v170\Microsoft.MakeFile.Targets(44,5): error MSB3073: The command ""C:\Program Files\Epic Games\UE_4.27\Engine\Build\BatchFiles\Build.bat" UE4_Assimp_TestEditor Win64 Development -Project="D:\Unreal Projects\UE4_Assimp_Test\UE4_Assimp_Test.uproject" -WaitMutex -FromMsBuild" exited with code 6.
1>Done building project "UE4_Assimp_Test.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

**Comment by inealey** [comment]
fixed by changing assimp build to "Release". 

Any further docs on using this plugin? for example, steps to set up the example project pictured at https://blueprintue.com/blueprint/inhg2zu3/

**Comment by irajsb** [comment]
Example is provided in releases tab
