### ISSUE TITLE
import skeleton mesh

### ISSUE THREAD

**Issue by king1107955613** [irajsb/UE4_Assimp#2]
HI, I want import skeleton mesh,can you do it

**Comment by irajsb** [comment]
![Screenshot 2021-08-04 113146](https://user-images.githubusercontent.com/36444724/128136525-eb3531ec-364d-4af5-9368-6767206a4e95.png)

Hello there ! I made some basic implementations for the bones! but its in experimental state ! pushing soon!

**Comment by king1107955613** [comment]
HI，I like this plug-in very much. Thank you for developing some functions for my suggestions. Thank you very much. I will give you feedback again after the test
