### ISSUE TITLE
Duplicate meshes are not spawned 

### ISSUE THREAD

**Issue by irajsb** [irajsb/UE4_Assimp#21]
#19

**Comment by irajsb** [comment]
https://github.com/irajsb/UE4_Assimp/releases/tag/MeshInstancing

**Comment by N1q** [comment]
Same model loaded almost completely, **yet** problems with small elements persists.

Sample 1

Blender:
![изображение](https://user-images.githubusercontent.com/33962843/189817239-9d4d4e7c-7984-4ba1-94a1-5516dbf1945c.png)
UE4:
![изображение](https://user-images.githubusercontent.com/33962843/189818214-9c93b965-00b4-4aca-96bd-7e1687154653.png)

Sample 2

Blender:
![изображение](https://user-images.githubusercontent.com/33962843/189816642-ac974cef-48a1-4793-9e40-263a078802ab.png)
UE4:
![изображение](https://user-images.githubusercontent.com/33962843/189818244-ccbe6532-23bb-422b-b39a-6bcd6ce2ec58.png)

**Comment by irajsb** [comment]
This is probably an issue in my conversion of assimp transforms to unreal. 
I've opened https://github.com/assimp/assimp/issues/4719 for it so probably someone can help us to do it correctly
