### ISSUE TITLE
The sample can not be implemented

### ISSUE THREAD

**Issue by wjswxc** [irajsb/UE4_Assimp#22]
I can't implement asynchrony。

**Comment by irajsb** [comment]
Async was removed in recent updates. Probably will add it back when I find a more clean way to implement it .

**Comment by wjswxc** [comment]
Thanks！One more question。Why does the model I imported using the sample blueprint have no material?

**Comment by wjswxc** [comment]
Also, the imported model is scattered.

**Comment by wjswxc** [comment]
<img width="1238" alt="Snipaste_2022-11-18_14-14-02" src="https://user-images.githubusercontent.com/64905471/202633795-c2603f6a-2b6f-4907-9200-aa761a71d143.png">
Look!It's hard to tell it's a plane.

**Comment by irajsb** [comment]
can you provide the model so I can see what issue is ?

**Comment by wjswxc** [comment]
Sure！Thank you so much!



---- Replied Message ----
| From | iraj ***@***.***> |
| Date | 11/18/2022 23:09 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [irajsb/UE4_Assimp] The sample can not be implemented (Issue #22) |

can you provide the model so I can see what issue is ?

**Comment by wjswxc** [comment]
https://github.com/wjswxc/Plane
I just uploaded that model to my repository.

**Comment by irajsb** [comment]
Is it necessary to use fbx? or can you use other formats ? I recommend glb because its binary (easier to read ) and it also stores textures better . If you want to use fbx use this option so it corrects the transforms ( We've issues with converting  transforms on some file formats automatically , hopefully someone good at math can fix it )
![image](https://user-images.githubusercontent.com/36444724/202758941-84be7fdd-75e5-4c3d-b7c0-66b448123805.png)


I've updated the code for colors . It required to multiply color value by 100 .will upload the updates soon 

![image](https://user-images.githubusercontent.com/36444724/202758800-abd6c68e-d63c-4f83-b226-01b62779039f.png)

**Comment by wjswxc** [comment]
Hhank you very much! Have you tried importing in other formats? Such as 3ds, obj, dae?

**Comment by irajsb** [comment]
https://github.com/irajsb/UE4_Assimp/releases/tag/v5.2.5

By the way seems like you are using older version of the code . You can find code for this version inside its level blueprint at project startup. Default sample material for imports is also included .

**Comment by wjswxc** [comment]
Sounds great！Thank you for your reminder.Love you.

**Comment by irajsb** [comment]
OBJ Result :
![image](https://user-images.githubusercontent.com/36444724/202766409-199d3ceb-2766-4e40-9336-bc2627c8d268.png)
DAE Result: 
![image](https://user-images.githubusercontent.com/36444724/202766525-8493606b-c97d-4bda-8fe1-d02fb063f423.png)

**Comment by wjswxc** [comment]
You are amazing！Thank you for your great help!

**Comment by wjswxc** [comment]
Dude, I'm sorry to report this to you. I found that the model material you imported may be correct for the first time when you use the modified project, but not necessarily the second time, and then the plane in fbx format is still scattered on my side. The gltf format cannot be imported. But the strange thing is that the 3ds format is intact, except that its texture is the default texture you set.

**Comment by irajsb** [comment]
for fbx use pretransform vertices(screenshot included few comments to the top of this page)  . for textures I recommended glb (binary) .

**Comment by wjswxc** [comment]
https://youtu.be/36XDVLZ6TSE
[https://youtu.be/36XDVLZ6TSE](https://youtu.be/36XDVLZ6TSE)

**Comment by irajsb** [comment]
https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Corset/glTF-Binary/Corset.glb
Can you try this ?

**Comment by irajsb** [comment]
The issue with plane model is it has some incorrect normal that you need to fix in modeling software 
![image](https://user-images.githubusercontent.com/36444724/203069190-f0be919f-6671-411a-b7b0-65c699145d3f.png)

**Comment by wjswxc** [comment]
Sure



---- Replied Message ----
| From | iraj ***@***.***> |
| Date | 11/21/2022 21:35 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [irajsb/UE4_Assimp] The sample can not be implemented (Issue #22) |

https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/Corset/glTF-Binary/Corset.glb
Can you try this ?

**Comment by wjswxc** [comment]
I don't know if you've noticed, but the model you're testing with only creates one Static Mesh when imported into UE, while I have multiple.And it is possible for a Static Mesh to have more than one Material.
Another problem is the lack of transparency in materials. What I mean is: if, I have a material that is black and white, and I only want the black to work, and the white to be transparent. It cannot be achieved. Of course, this problem is too complicated, and the number of times it is used is very small. Maybe we can first solve the problem that the material cannot be found when the model is imported into UE.

**Comment by irajsb** [comment]
If textures are not packed inside the file ( for example fbx files sometimes have a filepath to the texture ) then you have to import the texture manually . UV Coordinates have to be generated in modeling software as well. I think your problem is that you are not packing the textures correctly .  You can also generate the missing UV using this option 
![image](https://user-images.githubusercontent.com/36444724/203075137-abf32e3e-3863-4cb8-b499-06f611f5c1b1.png)

**Comment by irajsb** [comment]
![image](https://user-images.githubusercontent.com/36444724/203076792-55c24449-fc16-4ab6-8277-3a1a3086c99c.png)
the output of the load image sync is not connected to anywhere which means it does nothing . correct way is if embeded texture is valid (is valid is a node) then set embedded texture to texture param value and if its not embedded then read from path . However I recommend using formats that have embedded texture such as glb ( not gltf like the ones you sent in the video)

**Comment by wjswxc** [comment]
Yes, a large part of the current problems lie in the model I am looking for.

**Comment by wjswxc** [comment]
Thanks for your answer. wish you a happy life.
