### ISSUE TITLE
UE5.2 Failed to Import fbx Related issues

### ISSUE THREAD

**Issue by 9000miles** [irajsb/UE4_Assimp#34]
**Describe the bug**
1. UE5.2 asynchronous import function ImportScenesAsync will crash, and do not know how to call this function in the blueprint, can only copy from your example project

2. After packaging projects need AIMesh. CPP UAIMesh: : GetStaticMesh () function must add MeshDescriptionsParams. BFastBuild = true; Otherwise, it will crash, but the effect of loading after adding is wrong, and the whole model will become dark after the camera is close

**To Reproduce**

**Screenshots**
![image](https://github.com/irajsb/UE4_Assimp/assets/37586630/4f5e5db1-7b23-4c7d-8e6e-46d517b1a0ce)

**Sample file for testing **
Provide an optional sample file for testing .
![image](https://github.com/irajsb/UE4_Assimp/assets/37586630/60a235a0-0d86-4ad4-9969-ab996ec251fb)

**Comment by irajsb** [comment]
https://github.com/irajsb/UE4_Assimp/releases/tag/MajorBugFix I downloaded this and migrated to 5.2 and it works for me for that exact file 
![image](https://github.com/irajsb/UE4_Assimp/assets/36444724/569bc90b-a8a9-4438-8170-421b08727375)

**Comment by irajsb** [comment]
You can try using the other method which is using procedural mesh component . so instead of using static mesh spawn a procedural mesh component and get mesh data using GetMeshDataForProceduralMesh and connect it to procedural mesh component
