### ISSUE TITLE
Where does 'Microsoft/COMPointer.h' come from ?

### ISSUE THREAD

**Issue by ReynoldChen** [irajsb/UE4_Assimp#5]
Dear Irajsb,
Could you tell me where Microsoft/COMPointer.h comes from? 'Microsoft/COMPointer.h' is missing when compiling this plugin.

Env: UE4.25

Best Regards,
Reynold Chen

**Comment by irajsb** [comment]
Hi there ! this plugin is not compatible with  4.25 right now ( its for 26 and 27 ) . however I'll download 4.25 and fix the issues soon !

**Comment by irajsb** [comment]
Fixed in last commit. pull the new version and close this issue if it worked !

**Comment by ReynoldChen** [comment]
Irajsb,many thanks to you.
425 and 426 have the same head file. There is a change on 427.

#if ENGINE_MINOR_VERSION >26
#include "Microsoft/COMPointer.h"
#else
#include "Windows/COMPointer.h"
#endif

Best Regards,

**Comment by irajsb** [comment]
Fixed in 5.4.2 update .
