### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by mZe184** [irajsb/UE4_Assimp#6]
Hi There,

is there any sort of complete documentation to this? I struggle a bit with getting cameras working
Best regards
Matthias

**Comment by irajsb** [comment]
Hi ,try reading https://assimp-docs.readthedocs.io/en/v5.1.0/ .
other than that function names are mostly same and returns same set of data converted to UE formats . if a function that you are looking for is not findable in blueprints its because its not implemented yet!

**Comment by irajsb** [comment]
If you are looking for a function or a function is not working as expected leave its name below so I can try to fix it .

**Comment by mZe184** [comment]
> Hi ,try reading https://assimp-docs.readthedocs.io/en/v5.1.0/ . other than that function names are mostly same and returns same set of data converted to UE formats . if a function that you are looking for is not findable in blueprints its because its not implemented yet!

Could you please add the link to the README.md  as the link there show to the old documentation (only how to install).

**Comment by irajsb** [comment]
https://irajsb.github.io/UE4_Assimp/annotated.html
