### ISSUE TITLE
Compiling issues with UE 4.26.2 & VS 2017

### ISSUE THREAD

**Issue by henryprescott** [irajsb/UE4_Assimp#8]
Hey, thanks for your effort I'm hoping to make use of this in the future!

Just some feedback from trying to get things compiling and working in UE 4.26.2 - VS2017:

- [Following your guide](https://github.com/irajsb/UE4_Assimp/wiki/How-To-Build) generated x32 build, which I eventually ran into issue trying to load into the editor, I had to manually make a x64 configuration using cmake ui.
- [I also ran into this issue](https://github.com/irajsb/UE4_Assimp/issues/5), marked closed but isn't really fixed... I modified the file as @[ReynoldChen](https://github.com/ReynoldChen) suggested to solve the problem.
- [UE4_Assimp](https://github.com/irajsb/UE4_Assimp/tree/eb2a376304d735688bdc123ada51a704449b5470)/[Source](https://github.com/irajsb/UE4_Assimp/tree/eb2a376304d735688bdc123ada51a704449b5470/Source)/[ThirdParty](https://github.com/irajsb/UE4_Assimp/tree/eb2a376304d735688bdc123ada51a704449b5470/Source/ThirdParty)/[UE_AssimpLibrary](https://github.com/irajsb/UE4_Assimp/tree/eb2a376304d735688bdc123ada51a704449b5470/Source/ThirdParty/UE_AssimpLibrary)/UE_AssimpLibrary.Build.cs
This file has file versions hard coded for 2019, so maybe just point out to people that depending on their VS version they may need to adjust this?

Thanks!

**Comment by irajsb** [comment]
Update : 

Libs don't generate a suffix now .

I also updated to assimp 5.4 ( which means you probably need a fresh install ) .

You have to also set the build configuration to 64x in visual studio .
